config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                    new_author_session GET    /authors/sign_in(.:format)                                                               devise/sessions#new
#                        author_session POST   /authors/sign_in(.:format)                                                               devise/sessions#create
#                destroy_author_session DELETE /authors/sign_out(.:format)                                                              devise/sessions#destroy
#                   new_author_password GET    /authors/password/new(.:format)                                                          devise/passwords#new
#                  edit_author_password GET    /authors/password/edit(.:format)                                                         devise/passwords#edit
#                       author_password PATCH  /authors/password(.:format)                                                              devise/passwords#update
#                                       PUT    /authors/password(.:format)                                                              devise/passwords#update
#                                       POST   /authors/password(.:format)                                                              devise/passwords#create
#            cancel_author_registration GET    /authors/cancel(.:format)                                                                devise/registrations#cancel
#               new_author_registration GET    /authors/sign_up(.:format)                                                               devise/registrations#new
#              edit_author_registration GET    /authors/edit(.:format)                                                                  devise/registrations#edit
#                   author_registration PATCH  /authors(.:format)                                                                       devise/registrations#update
#                                       PUT    /authors(.:format)                                                                       devise/registrations#update
#                                       DELETE /authors(.:format)                                                                       devise/registrations#destroy
#                                       POST   /authors(.:format)                                                                       devise/registrations#create
#                            home_index GET    /home/index(.:format)                                                                    home#index
#                                  root GET    /                                                                                        home#index
#                         post_elements GET    /posts/:post_id/elements(.:format)                                                       authors/elements#index
#                                       POST   /posts/:post_id/elements(.:format)                                                       authors/elements#create
#                      new_post_element GET    /posts/:post_id/elements/new(.:format)                                                   authors/elements#new
#                     edit_post_element GET    /posts/:post_id/elements/:id/edit(.:format)                                              authors/elements#edit
#                          post_element GET    /posts/:post_id/elements/:id(.:format)                                                   authors/elements#show
#                                       PATCH  /posts/:post_id/elements/:id(.:format)                                                   authors/elements#update
#                                       PUT    /posts/:post_id/elements/:id(.:format)                                                   authors/elements#update
#                                       DELETE /posts/:post_id/elements/:id(.:format)                                                   authors/elements#destroy
#                                 posts GET    /posts(.:format)                                                                         authors/posts#index
#                                       POST   /posts(.:format)                                                                         authors/posts#create
#                              new_post GET    /posts/new(.:format)                                                                     authors/posts#new
#                             edit_post GET    /posts/:id/edit(.:format)                                                                authors/posts#edit
#                                  post GET    /posts/:id(.:format)                                                                     authors/posts#show
#                                       PATCH  /posts/:id(.:format)                                                                     authors/posts#update
#                                       PUT    /posts/:id(.:format)                                                                     authors/posts#update
#                                       DELETE /posts/:id(.:format)                                                                     authors/posts#destroy
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :authors
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  scope module: 'authors' do
  	resources :posts do
  	  resources :elements
  	end
  end
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text
#  published    :boolean
#  published_at :datetime
#  author_id    :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Post < ApplicationRecord
  belongs_to :author
  has_many :elements

  has_one_attached :header_image
end

app/controllers/authors/elements_controller.rb
module Authors
  class ElementsController < ApplicationController
    before_action :set_post
    before_action :set_element, only: [:update, :destroy]

    # POST /elements
    def create
      @element = @post.elements.build(element_params())


      note = nil
      if !@element.save
        note = @element.errors.full_messages.join(". ") << "."
      end

      redirect_to edit_post_path(@post), notice: note

    end

    # PATCH/PUT /elements/1
    def update
      @element.update(element_params)
      redirect_to edit_post_path(@element.post)
    end

    # DELETE /elements/1
    def destroy
      @element.destroy
      redirect_to edit_post_path(@post), notice: 'Element was successfully destroyed.'
    end

    private
      def set_post
        @post = current_author.posts.find(params[:post_id])
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_element
        @element = @post.elements.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def element_params
        params.require(:element).permit(:element_type, :content, :image)
      end
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: [:edit, :update, :destroy]

    # GET /posts
    def index
      @posts = current_author.posts
    end

    # GET /posts/new
    def new
      @post = current_author.posts.build
    end

    # GET /posts/1/edit
    def edit
      # @paragraph = @post.elements.build(element_type: 'paragraph')
      # @image = @post.elements.build(element_type: 'image')
      @element = @post.elements.build
    end

    # POST /posts
    def create
      @post = current_author.posts.build(post_params)

      if @post.save
        redirect_to edit_post_path(@post.id), notice: 'Post was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to edit_post_path(@post.id), notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        # only see posts that belong to the author
        @post = current_author.posts.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:title, :description, :header_image)
      end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!

  # Specify layout file
  # (Different look for authors)
  layout 'authors'
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :header_image %>
    <%= form.file_field :header_image, class: 'form-control' %>
    
    <div class="mt-1">
      <small>Current image:</small>
      <% if post.header_image.present? %>
        <%= image_tag(post.header_image, width: '100%') %>
      <% end %>
    </div>
    
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <%= link_to 'Back', posts_path, class: 'btn btn-dark mb-3' %>
    <div class="card">
      <div class="card-header">
        <h6 class="card-title mb-0">Editing Post</h6>
      </div>
      <div class="card-body">
        <%= render 'form', post: @post %>
      </div>
      <div class="card-footer">
        <% if @post.published? %>
          <a href="#" 
            class="btn btn-secondary btn-block" 
            data-reflex="click->PublisherReflex#unpublish"
            data-post-id='<%= @post.id %>'>
            Unpublish
          </a>
        <% else %>
          <a href="#" 
            class="btn btn-dark btn-block" 
            data-reflex="click->PublisherReflex#publish"
            data-post-id='<%= @post.id %>'>
            Publish
          </a>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="mb-3">
      <%= form_with(model: [@post, @element], html: {class: 'float-left mr-2'}) do |form| %>
        <%= form.hidden_field :element_type, value: 'paragraph' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          <i class="fas fa-paragraph"></i>
        <% end %>
      <% end %>
      <%= form_with(model: [@post, @element]) do |form| %>
        <%= form.hidden_field :element_type, value: 'image' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          <i class="fas fa-image"></i>
        <% end %>
      <% end %>
    </div>    
    <div class="card mb-5">
      <div class="card-header text-right">
        <% if @post.published? %>
          <b>Published</b> <%= time_ago_in_words(@post.published_at) %> ago
        <% else %>
          Unpublished
        <% end %>
      </div>
      
      <div class="card-body pt-5" data-controller="elements">
        <ul id="elements" data-action="drop->elements#sort">
          <% @post.elements.order(:position).each do |element| %>
            <% if element.persisted? %>
              <li data-id="<%= element.id %>" class="element-item">
                <% if element.paragraph? %>
                  <div class="mb-4 p-3 paragraph">
                    <div class="paragraph-content">
                      <% if element.content.present? %>
                        <%= element.content %>
                      <% else %>
                        Click to add content.
                      <% end %>
                    </div>
                    <div class="paragraph-form d-none">
                      <%= form_with(model: [@post, element]) do |form| %>
                        <%= form.rich_text_area :content %>
                        <div class="mt-3 d-flex justify-content-between">
                          <div>
                            <%= form.submit "Save", class: "btn btn-primary" %>
                            <a href="#" class="cancel btn btn-secondary">Cancel</a>
                          </div>
                          <%= link_to 'Delete', post_element_path(@post, element), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure?"} %>
                        </div>                
                      <% end %>
                    </div>
                  </div>
                <% elsif element.image? %>
                  <div class="mb-4 p-3 image">
                    <% if element.image.present? %>
                      <%= link_to post_element_path(@post, element), method: :delete, class: 'delete-btn btn btn-dark mt-2 float-right', data: {confirm: "Are you sure?"} do %>
                        <i class="fas fa-times"></i>
                      <% end %>
                      <%= image_tag(element.image) %>
                    <% else %>
                      <%= form_with(model: [@post, element]) do |form| %>
                        <%= form.file_field :image %>
                        <div class="mt-3">
                          <%= form.submit "Save", class: "btn btn-primary" %>
                          <a href="#" class="cancel btn btn-secondary">Cancel</a>
                        </div>                
                      <% end %>
                    <% end %>
                  </div>              
                <% end %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/authors/posts/index.html.erb
<h4 class="d-flex justify-content-between mb-4">
  <span>Posts</span>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
</h4>

<% @posts.each do |post| %>
  <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
    <div class="card mb-3 post-card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2">
            <% if post.header_image.present? %>
              <div class="header-img" style="background-image: url(<%= url_for(post.header_image) %>);">
              </div>
            <% end %>
          </div>
          <div class="col-md-10">
            <% if post.published? %>
              <span class="badge badge-primary mb-3">Published</span>
            <% else %>
              <span class="badge badge-secondary mb-3">Unpublished</span>
            <% end %>
            <h5 class="card-title text-dark mb-2"><%= post.title %></h5>
            <p class="text-secondary mb-0"><%= post.description %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/authors/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>